notifications:
  email: false
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX

language: node_js

node_js:
  - "node"

env:
  - img=existdb/existdb:latest
  - img=existdb/existdb:release

services:
  - docker

cache:
  npm: true
  directories:
    - ~/.cache

before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img
  - docker start exist-ci

install:
  - npm ci

before_script:
  # exist needs time
  - sleep 30
  - docker ps

script:
  - cypress run --record --key $CYPRESS_RECORD_KEY
